id: P004351
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS19338
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  volumes:
    7afe723dbe744035a6c92d4bebf24fa0:
      image_group_id: I8LS19340
      title: ''
      volume_number: 1
      total_pages: 580
      base_file: v001.txt
